import "../styles/estilos.css"
import Nav from "@/styles/components/Nav"


export const metadata = {
  title: 'FVL',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
      </body>
    </html>
  )
}
